/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion;

import Modelo.Operador;
import Vista.MainMenu;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
public class CRUD_OPERADORES extends javax.swing.JFrame {
    MainMenu menu;
    Operador opera;
    Conexion con1= new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    public CRUD_OPERADORES(MainMenu menu) {
        this.menu=menu;
        initComponents();
        setLocationRelativeTo(null);
        opera = new Operador(this);
        opera.consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        optionRol = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Crear = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Regresar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        TabsOperadores = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaOperadorRegular = new javax.swing.JTable();
        ScrollRegulares = new javax.swing.JScrollPane();
        TablaOperadorDespedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 138, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIÓN DE OPERADORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(31, 110, 140));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres");

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos");

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI");

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono");

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID");

        txtNombre.setBackground(new java.awt.Color(132, 167, 161));
        txtNombre.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtApellido.setBackground(new java.awt.Color(132, 167, 161));
        txtApellido.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtDNI.setBackground(new java.awt.Color(132, 167, 161));
        txtDNI.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(255, 255, 255));
        txtDNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtTelefono.setBackground(new java.awt.Color(132, 167, 161));
        txtTelefono.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(132, 167, 161));
        txtID.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña");

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rol");

        txtUsuario.setBackground(new java.awt.Color(132, 167, 161));
        txtUsuario.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        txtContraseña.setBackground(new java.awt.Color(132, 167, 161));
        txtContraseña.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        txtEdad.setBackground(new java.awt.Color(132, 167, 161));
        txtEdad.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        optionRol.setBackground(new java.awt.Color(132, 167, 161));
        optionRol.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        optionRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador" }));
        optionRol.setToolTipText("");
        optionRol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        optionRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido)
                    .addComponent(txtDNI)
                    .addComponent(txtTelefono)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtContraseña)
                    .addComponent(txtEdad)
                    .addComponent(optionRol, 0, 487, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(optionRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1330, 230));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BASE DE DATOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        Crear.setBackground(new java.awt.Color(14, 41, 84));
        Crear.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        Crear.setForeground(new java.awt.Color(255, 255, 255));
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        Crear.setText("Crear");
        Crear.setBorder(null);
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        jPanel1.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, 40));

        Modificar.setBackground(new java.awt.Color(14, 41, 84));
        Modificar.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.setBorder(null);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 140, 40));

        Eliminar.setBackground(new java.awt.Color(14, 41, 84));
        Eliminar.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        Eliminar.setBorder(null);
        Eliminar.setBorderPainted(false);
        Eliminar.setLabel("Dar de baja");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 150, 40));
        Eliminar.getAccessibleContext().setAccessibleDescription("");

        Limpiar.setBackground(new java.awt.Color(14, 41, 84));
        Limpiar.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.setBorder(null);
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 110, 40));

        Regresar.setBackground(new java.awt.Color(14, 41, 84));
        Regresar.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        Regresar.setText("Regresar");
        Regresar.setBorder(null);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 130, 40));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        TabsOperadores.setBackground(new java.awt.Color(14, 41, 84));
        TabsOperadores.setForeground(new java.awt.Color(255, 255, 255));
        TabsOperadores.setFont(new java.awt.Font("SF Pro Display", 1, 17)); // NOI18N
        TabsOperadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabsOperadoresMouseClicked(evt);
            }
        });

        TablaOperadorRegular.setBackground(new java.awt.Color(132, 167, 161));
        TablaOperadorRegular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaOperadorRegular.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        TablaOperadorRegular.setForeground(new java.awt.Color(255, 255, 255));
        TablaOperadorRegular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol", "DNI", "Telefono", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaOperadorRegular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOperadorRegularMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaOperadorRegular);

        TabsOperadores.addTab("Regulares", jScrollPane4);

        ScrollRegulares.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        ScrollRegulares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrollRegularesMouseClicked(evt);
            }
        });

        TablaOperadorDespedidos.setBackground(new java.awt.Color(132, 167, 161));
        TablaOperadorDespedidos.setFont(new java.awt.Font("SF Pro Display", 0, 17)); // NOI18N
        TablaOperadorDespedidos.setForeground(new java.awt.Color(255, 255, 255));
        TablaOperadorDespedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Rol", "DNI", "Fecha de baja", "Razón de baja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaOperadorDespedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOperadorDespedidosMouseClicked(evt);
            }
        });
        ScrollRegulares.setViewportView(TablaOperadorDespedidos);

        TabsOperadores.addTab("Cesados", ScrollRegulares);

        jPanel1.add(TabsOperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1300, 240));
        TabsOperadores.getAccessibleContext().setAccessibleName("asfasf");

        jScrollPane6.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        menu.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        opera.nuevo();        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        opera.eliminar();
        opera.consultar();
        opera.nuevo();// TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        opera.Modificar();
        opera.consultar();
        opera.nuevo();        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed

        opera.Agregar();
        opera.consultar();
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearActionPerformed

    private void optionRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionRolActionPerformed

    }//GEN-LAST:event_optionRolActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void TablaOperadorDespedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOperadorDespedidosMouseClicked
        int fila = TablaOperadorDespedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Operador no seleccionado");

        } else{
            idc = Integer.parseInt((String) TablaOperadorDespedidos.getValueAt(fila, 0).toString());
            String nombre = (String) TablaOperadorDespedidos.getValueAt(fila, 1);
            String apellido = (String) TablaOperadorDespedidos.getValueAt(fila, 2);
            String user = (String) TablaOperadorDespedidos.getValueAt(fila, 3);
            String contra = (String) TablaOperadorDespedidos.getValueAt(fila, 4);
            String rol =(String) TablaOperadorDespedidos.getValueAt(fila, 5);
            String DNI = (String) TablaOperadorDespedidos.getValueAt(fila, 6);
            String telefono = (String) TablaOperadorDespedidos.getValueAt(fila, 7);
            int edad = Integer.parseInt((String) TablaOperadorDespedidos.getValueAt(fila, 8).toString());
            txtID.setText(""+idc);
            txtNombre.setText(nombre);
            txtApellido.setText(apellido);
            txtUsuario.setText(user);
            txtContraseña.setText(contra);
            optionRol.setSelectedItem(rol);
            txtDNI.setText(DNI);
            txtTelefono.setText(telefono);
            txtEdad.setText(""+edad);
        }
    }//GEN-LAST:event_TablaOperadorDespedidosMouseClicked

    private void TablaOperadorRegularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOperadorRegularMouseClicked
        int fila = TablaOperadorRegular.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Operador no seleccionado");

        } else{
            idc = Integer.parseInt((String) TablaOperadorRegular.getValueAt(fila, 0).toString());
            String nombre = (String) TablaOperadorRegular.getValueAt(fila, 1);
            String apellido = (String) TablaOperadorRegular.getValueAt(fila, 2);
            String user = (String) TablaOperadorRegular.getValueAt(fila, 3);
            String contra = (String) TablaOperadorRegular.getValueAt(fila, 4);
            String rol =(String) TablaOperadorRegular.getValueAt(fila, 5);
            String DNI = (String) TablaOperadorRegular.getValueAt(fila, 6);
            String telefono = (String) TablaOperadorRegular.getValueAt(fila, 7);
            int edad = Integer.parseInt((String) TablaOperadorRegular.getValueAt(fila, 8).toString());
            txtID.setText(""+idc);
            txtNombre.setText(nombre);
            txtApellido.setText(apellido);
            txtUsuario.setText(user);
            txtContraseña.setText(contra);
            optionRol.setSelectedItem(rol);
            txtDNI.setText(DNI);
            txtTelefono.setText(telefono);
            txtEdad.setText(""+edad);
        }
    }//GEN-LAST:event_TablaOperadorRegularMouseClicked

    private void TabsOperadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabsOperadoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabsOperadoresMouseClicked

    private void ScrollRegularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollRegularesMouseClicked
        opera.limpiarTabla_cesados();        // TODO add your handling code here:
    }//GEN-LAST:event_ScrollRegularesMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Modificar;
    private javax.swing.JToggleButton Regresar;
    private javax.swing.JScrollPane ScrollRegulares;
    public javax.swing.JTable TablaOperadorDespedidos;
    public javax.swing.JTable TablaOperadorRegular;
    private javax.swing.JTabbedPane TabsOperadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JComboBox<String> optionRol;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
