
package Vista;

import Vista.MainMenu;
import Modelo.Bus;
import Modelo.BusCRUD;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class CRUD_Buses extends javax.swing.JFrame {

    MainMenu menu;
    private BusCRUD busCRUD = new BusCRUD();
    private DefaultTableModel modelo;

    public CRUD_Buses(MainMenu menu) {
        this.menu=menu;
        initComponents();
        setLocationRelativeTo(null);
        configurarTipoBus();
        consultar();
    }
        // Configura la capacidad según el tipo de bus seleccionado
    private void configurarTipoBus() {
        Tipos.addActionListener(evt -> {
            String tipoSeleccionado = Tipos.getSelectedItem().toString();
            switch (tipoSeleccionado) {
                case "Estándar":
                    Capacidad.setText("60");
                    break;
                case "Premium":
                    Capacidad.setText("50");
                    break;
                case "Vip":
                    Capacidad.setText("40");
                    break;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Capacidad = new javax.swing.JTextField();
        Estado = new javax.swing.JComboBox<>();
        Tipos = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        Label_Bus = new javax.swing.JLabel();
        Label_Bus1 = new javax.swing.JLabel();
        Label_Bus3 = new javax.swing.JLabel();
        Label_Bus4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBus = new javax.swing.JTable();
        Eliminar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 138, 153));

        jPanel1.setBackground(new java.awt.Color(46, 138, 153));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bus1.png"))); // NOI18N
        jLabel1.setText("Buses");
        jLabel1.setAlignmentY(0.0F);

        jPanel2.setBackground(new java.awt.Color(31, 110, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        Capacidad.setEditable(false);
        Capacidad.setBackground(new java.awt.Color(132, 167, 161));
        Capacidad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadActionPerformed(evt);
            }
        });

        Estado.setBackground(new java.awt.Color(132, 167, 161));
        Estado.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Estado.setForeground(new java.awt.Color(255, 255, 255));
        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Viaje", "Mantenimiento" }));

        Tipos.setBackground(new java.awt.Color(132, 167, 161));
        Tipos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estándar", "Premium", "Vip" }));

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(132, 167, 161));
        ID.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        Label_Bus.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        Label_Bus.setText("Tipo");

        Label_Bus1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        Label_Bus1.setText("Capacidad");

        Label_Bus3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        Label_Bus3.setText("Estado");

        Label_Bus4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        Label_Bus4.setText("Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Label_Bus)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_Bus1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tipos, 0, 526, Short.MAX_VALUE)
                    .addComponent(Capacidad))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_Bus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Bus4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addComponent(Estado, 0, 527, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Bus))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Bus1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Bus3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Bus4))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(46, 138, 153));

        TablaBus.setBackground(new java.awt.Color(132, 167, 161));
        TablaBus.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        TablaBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Capacidad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaBusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaBus);
        if (TablaBus.getColumnModel().getColumnCount() > 0) {
            TablaBus.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaBus.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Eliminar.setBackground(new java.awt.Color(14, 41, 84));
        Eliminar.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar1.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Crear.setBackground(new java.awt.Color(14, 41, 84));
        Crear.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        Crear.setForeground(new java.awt.Color(255, 255, 255));
        Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(14, 41, 84));
        Buscar.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(14, 41, 84));
        Modificar.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(14, 41, 84));
        jButton2.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(14, 41, 84));
        jButton1.setFont(new java.awt.Font("Serif", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Base de datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(578, 578, 578))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un bus para eliminar.");
            return;
        }

        int id = Integer.parseInt(ID.getText());
        if (busCRUD.eliminarBus(id)) {
            JOptionPane.showMessageDialog(this, "Bus eliminado exitosamente.");
            consultar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el bus.");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if (ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un bus para modificar.");
            return;
        }

        int id = Integer.parseInt(ID.getText());
        String tipo = Tipos.getSelectedItem().toString();
        String estado = Estado.getSelectedItem().toString();
        int capacidad = Integer.parseInt(Capacidad.getText());

        Bus bus = new Bus(id, tipo, capacidad, estado);
        if (busCRUD.modificarBus(bus)) {
            JOptionPane.showMessageDialog(this, "Bus modificado exitosamente.");
            consultar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el bus.");
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        String tipo = Tipos.getSelectedItem().toString();
        String estado = Estado.getSelectedItem().toString();
        int capacidad;
        try {
            capacidad = Integer.parseInt(Capacidad.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Capacidad no válida.");
            return;
        }

        Bus bus = new Bus(0, tipo, capacidad, estado);
        if (busCRUD.crearBus(bus)) {
            JOptionPane.showMessageDialog(this, "Bus creado exitosamente.");
            consultar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el bus.");
        }
    }//GEN-LAST:event_CrearActionPerformed

    private void TablaBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBusMouseClicked
        int fila = TablaBus.getSelectedRow();
        if (fila != -1) {
            ID.setText(TablaBus.getValueAt(fila, 0).toString());
            Tipos.setSelectedItem(TablaBus.getValueAt(fila, 1).toString());
            Capacidad.setText(TablaBus.getValueAt(fila, 2).toString());
            Estado.setSelectedItem(TablaBus.getValueAt(fila, 3).toString());
        }
    }//GEN-LAST:event_TablaBusMouseClicked

    private void CapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String tipo = Tipos.getSelectedItem().toString();
        String estado = Estado.getSelectedItem().toString();

        List<Bus> buses = busCRUD.buscarBus(tipo, estado);
        limpiarTabla();
        for (Bus bus : buses) {
            modelo.addRow(new Object[]{bus.getId(), bus.getTipo(), bus.getCapacidad(), bus.getEstado()});
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ID.setText("");
        Capacidad.setText("");
        Tipos.setSelectedIndex(0); // Selecciona el primer elemento (por ejemplo, "Estándar")
        Estado.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

      
    private void consultar() {
        List<Bus> buses = busCRUD.buscarBus("", ""); // Traer todos los buses sin filtro
        modelo = (DefaultTableModel) TablaBus.getModel();
        limpiarTabla(); // Limpiar la tabla antes de añadir nuevos datos

        for (Bus bus : buses) {
            modelo.addRow(new Object[]{bus.getId(), bus.getTipo(), bus.getCapacidad(), bus.getEstado()});
        }
    }
    private void limpiarTabla() {
        modelo.setRowCount(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Capacidad;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Eliminar;
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Label_Bus;
    private javax.swing.JLabel Label_Bus1;
    private javax.swing.JLabel Label_Bus3;
    private javax.swing.JLabel Label_Bus4;
    private javax.swing.JButton Modificar;
    private javax.swing.JTable TablaBus;
    private javax.swing.JComboBox<String> Tipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
